name: Mirror to Bitbucket Repo
run-name: ${{github.actor}} CI/CD Pipeline on ${{github.ref_name}}
on:
  push:
    branches-ignore:
      - " ga-ignore-"

concurrency:
  group: git-mirror

jobs:
  size:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Check the size of the repository
        run: |
          SIZE=$(du -skh --exclude=.git | cut -f1)
          echo "The size of the repository is $SIZE"
          if [ $SIZE -gt 30000 ]; then
            echo "Size of the repository is too big"
            exit 1
          fi

  git-mirror:
    runs-on: self-hosted
    if: github.event_name == 'push'
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_KNOWN_HOSTS: ${{ secrets.GIT_SSH_KNOWN_HOSTS }}
          SSH_PRIVATE_KEY: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
        with:
          source-repo: "${{ github.repository }}"
          destination-repo: "${{ vars.MIRROR_URL }}"
        name: Mirror to Bitbucket Repo
