name: CI/CD
run-name: ${{github.actor}} CI/CD Pipeline on ${{github.ref_name}}
on:
  push:
    branches-ignore:
      - " ga-ignore-"

jobs:
  size:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Check the size of the repository
        run: |
          SIZE=$(du -skh --exclude=.git | cut -f1)
          echo "The size of the repository is $SIZE"
          if [ $SIZE -gt 30000 ]; then
            echo "Size of the repository is too big"
            exit 1
          fi

  push_to_mirror:
    runs-on: self-hosted
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url:
            ${{ vars.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.GIT_SSH_PRIVATE_KEY }}
